language: python

python:
   - "3.7"
   - "3.8"

install:

   - pip install -r requirements.txt
   - python setup.py install

before_install:

  - python --version
  - pip install -U pip
  - pip install -U pytest

script:

   - nohup python3 example.py
   - pytest tests/tests_asyncapy.py

virtualenv:

   system_site_packages = true
