language: python

python:
   - "3.7"
   - "3.8"

install:			 
  - sudo python3 setup.py install
                                                   
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install trio
  - sudo python setup.py instal
 

script:
   - nohup python example.py
   - pytest tests/tests_asyncapy.py

