language: python

python:
   - "3.7"
   - "3.8"

sudo: required

os: linux

install:

   - sudo python3 -m pip install -r requirements.txt
   - sudo python3 setup.py install

before_install:

  - python --version
  - pip install -U pip
  - pip install -U pytest

script:

   - nohup python3 example.py
   - pytest tests/tests_asyncapy.py

