language: python

python:
   - "3.7"
   - "3.8"

install:			 
  - echo "Done"
                                                   
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install trio setuptools wheel
  - python travis_setup.py install 
      
script:
   - nohup python example.py &
   - pytest tests/tests_asyncapy.py

